# Generated by Django 5.1.1 on 2024-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Experience', models.CharField(max_length=50)),
            ],
        ),
    ]
