# Generated by Django 5.1.1 on 2024-10-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='PhoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
