# Generated by Django 5.1.1 on 2024-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_candidate_email_alter_candidate_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.IntegerField(max_length=20)),
                ('req_name', models.CharField(max_length=100)),
            ],
        ),
    ]
