# Generated by Django 5.1.1 on 2024-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestid',
            name='req_id',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requestid',
            name='req_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
